# Generated by Django 2.1.3 on 2019-01-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20190122_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='needs_help_with',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wants_expert',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
