# Generated by Django 2.1.3 on 2019-02-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20190124_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twilio_user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
