# Generated by Django 2.1.3 on 2019-01-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(default='e.g. Advice on statistics', max_length=200, null=True),
        ),
    ]
