# Generated by Django 2.0.5 on 2018-11-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181120_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Please provide some detail on what you would like to learn or discuss', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Video Call', max_length=200, null=True),
        ),
    ]
