# Generated by Django 2.0.5 on 2018-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181123_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='completeDateTime',
            field=models.DateTimeField(default='', null=True, verbose_name='Booking Time'),
        ),
    ]
