# Generated by Django 2.0.5 on 2018-11-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20181130_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='completeDateTime',
            field=models.DateTimeField(null=True, verbose_name='Booking Time'),
        ),
    ]
