# Generated by Django 2.0.5 on 2018-12-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20181211_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='confirmation',
            name='expert_confirming',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
