# Generated by Django 2.0.5 on 2018-12-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20181211_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
