# Generated by Django 2.1.3 on 2018-12-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_tutorial',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Title/subject of your video call', max_length=200, null=True),
        ),
    ]
