# Generated by Django 2.1.3 on 2019-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
